---
language: ruby
cache:
  - bundler
  - apt
rvm:
  - ruby-2.0.0

script: "bundle exec rspec --colour"

env:
  global:
    - RACK_ENV=test
    - SERVICE_NAME=rdio-service
    - RDIO_KEY=YOUR_RDIO_KEY
    - RDIO_SECRET=YOUR_RDIO_SECRET
    - RDIO_ACCESS_TOKEN=YOUR_ACCESS_TOKEN
    - RDIO_ACCESS_SECRET=YOUR_ACCESS_SECRET
